export const sampleTournamentData = {
  meta: {
    fileName: 'demo.xlsx',
    loadedAt: new Date().toISOString(),
    sheets: ['Resultados', 'Posiciones', 'Próxima Fecha', 'Goleadores', 'Fair Play'],
  },
  rounds: ['Fecha 8', 'Fecha 7'],
  results: [
    {
      id: 'r1',
      round: 'Fecha 8',
      homeTeam: 'Tigres UTN',
      awayTeam: 'Deportivo Norte',
      homeGoals: 2,
      awayGoals: 1,
      venue: 'Cancha 1',
      kickoff: '18:00',
    },
    {
      id: 'r2',
      round: 'Fecha 8',
      homeTeam: 'Atlético Sur',
      awayTeam: 'Los Pibes FC',
      homeGoals: 0,
      awayGoals: 0,
      venue: 'Cancha 2',
      kickoff: '19:30',
    },
    {
      id: 'r3',
      round: 'Fecha 7',
      homeTeam: 'Tigres UTN',
      awayTeam: 'Atlético Sur',
      homeGoals: 1,
      awayGoals: 1,
      venue: 'Cancha 1',
      kickoff: '18:30',
    },
  ],
  standings: [
    { id: 'p1', team: 'Tigres UTN', pj: 8, g: 6, e: 1, p: 1, gf: 15, gc: 6, dif: 9, pts: 19 },
    { id: 'p2', team: 'Deportivo Norte', pj: 8, g: 5, e: 2, p: 1, gf: 12, gc: 7, dif: 5, pts: 17 },
    { id: 'p3', team: 'Atlético Sur', pj: 8, g: 3, e: 4, p: 1, gf: 9, gc: 6, dif: 3, pts: 13 },
    { id: 'p4', team: 'Los Pibes FC', pj: 8, g: 2, e: 1, p: 5, gf: 6, gc: 13, dif: -7, pts: 7 },
  ],
  fixture: [
    {
      id: 'f1',
      round: 'Fecha 9',
      kickoff: '17:00',
      venue: 'Cancha 3',
      homeTeam: 'Deportivo Norte',
      awayTeam: 'Atlético Sur',
    },
    {
      id: 'f2',
      round: 'Fecha 9',
      kickoff: '19:00',
      venue: 'Cancha 1',
      homeTeam: 'Tigres UTN',
      awayTeam: 'Los Pibes FC',
    },
  ],
  scorers: [
    { id: 's1', player: 'L. Gómez', team: 'Tigres UTN', goals: 8 },
    { id: 's2', player: 'M. Pérez', team: 'Deportivo Norte', goals: 6 },
    { id: 's3', player: 'D. Silva', team: 'Atlético Sur', goals: 5 },
  ],
  fairPlay: [
    { id: 'fp1', team: 'Atlético Sur', points: 4 },
    { id: 'fp2', team: 'Tigres UTN', points: 6 },
    { id: 'fp3', team: 'Deportivo Norte', points: 8 },
    { id: 'fp4', team: 'Los Pibes FC', points: 10 },
  ],
  categoryOrder: ['A', 'B', 'C'],
  categories: {
    A: {
      rounds: ['Fecha 8', 'Fecha 7'],
      results: [
        {
          id: 'r1',
          round: 'Fecha 8',
          homeTeam: 'Tigres UTN',
          awayTeam: 'Deportivo Norte',
          homeGoals: 2,
          awayGoals: 1,
          venue: 'Cancha 1',
          kickoff: '18:00',
        },
      ],
      standings: [
        { id: 'p1', team: 'Tigres UTN', pj: 8, g: 6, e: 1, p: 1, gf: 15, gc: 6, dif: 9, pts: 19 },
      ],
      fixture: [
        {
          id: 'f1',
          round: 'Fecha 9',
          kickoff: '17:00',
          venue: 'Cancha 3',
          homeTeam: 'Deportivo Norte',
          awayTeam: 'Atlético Sur',
        },
      ],
      scorers: [{ id: 's1', player: 'L. Gómez', team: 'Tigres UTN', goals: 8 }],
      fairPlay: [{ id: 'fp1', team: 'Atlético Sur', points: 4 }],
    },
    B: { rounds: [], results: [], standings: [], fixture: [], scorers: [], fairPlay: [] },
    C: { rounds: [], results: [], standings: [], fixture: [], scorers: [], fairPlay: [] },
  },
  sanctions: [
    {
      id: 'san-1',
      name: 'Jugador Demo',
      team: 'Tigres UTN',
      category: 'A',
      expulsionDate: 'Fecha 7',
      article: '3.C.2',
      sanction: '1 fecha',
      until: 'Fecha 9',
    },
  ],
  byes: {
    A: [{ round: 'Fecha 9', team: 'Los Pibes FC' }],
    B: [],
    C: [],
  },
};
